version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels:
      - dependencies
      - automation
    commit-message:
      prefix: chore
    open-pull-requests-limit: 5
