changelog:
  categories:
    - title: New components
      labels:
        - enhancement
        - component
    - title: Corrections
      labels:
        - bug
        - correction
    - title: Documentation
      labels:
        - documentation
    - title: Maintenance
      labels:
        - maintenance
        - dependencies
        - automation
    - title: Other changes
      labels:
        - "*"
